<style>
    .contact-us {
        max-width: 556px;
        font-family: Arial, Helvetica, sans-serif;
        background: #ffffff;
        border: 1px solid #ececec;
        margin: 0 auto;
    }

    /* Tabs labels */
    .contact-us .contact-us__tabs {
        display: block;
        font-size: 0;
        padding: 0;
        margin: 0;
    }

    .contact-us .contact-us__tab {
        display: inline-flex;
        justify-content: center;
        align-items: center;
        width: 50%;
        min-height: 47px;
        color: #525252;
        text-shadow: 0 0 0 rgba(82, 82, 82, 0.4);
        font-size: 13px;
        letter-spacing: 0.2px;
        background: #f9f9f9;
        text-transform: uppercase;
        vertical-align: top;
        cursor: pointer;
    }

    .contact-us .contact-us__tab.active {
        color: #e31837;
        text-shadow: 0 0 0 rgba(227, 24, 25, 0.4);
        border-bottom: 2px solid #e31837;
    }

    /* Tabs Content */
    .contact-us .contact-us__tab-content {
        display: none;
    }

    .contact-us .contact-us__tab-content.active {
        display: block;
    }

    /*Call us section*/
    .contact-us .call-us__title {
        display: none;
    }

    .contact-us .call-us__row-title {
        color: #525252;
        font-size: 16px;
        font-weight: bold;
        line-height: 1.5;
        letter-spacing: 0.55px;
        margin: 0;
    }

    .contact-us .call-us__contact-row {
        padding: 16px 16px 0 16px;
        border-bottom: 1px solid #e7e7e7;
    }

    .contact-us .call-us__contact {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 8px;
        border-bottom: 1px solid #e7e7e7;
    }

    .contact-us .call-us__contact:last-child {
        border-bottom: none;
    }

    .contact-us .call-us__phone {
        display: inline-block;
        font-size: 16px;
        color: #525252;
        line-height: 1.5;
    }

    .contact-us .call-us__phone-button {
        display: inline-block;
        width: 32px;
        height: 32px;
        background-image: url(https://i.allo.ua/skin/frontend/enterprise/allomobile/images/sprite-all.svg?v=1.1);
        background-repeat: no-repeat;
        background-position: -272px -620px;
        background-size: 628px 1096px;
        background-color: #e31837;
        border-radius: 3px;
        box-shadow: 0 2px 4px -2px #525252;
    }

    .contact-us .call-us__schedule-row {
        padding: 16px 16px 0 16px;
        border-bottom: 1px solid #e7e7e7;
    }

    .contact-us .call-us__schedule {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 16px;
        color: #525252;
        line-height: 1.5;
        padding: 8px;
    }

    .contact-us .call-us__map-row {
        padding: 16px 16px 0 16px;
    }

    .contact-us .call-us__map {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 16px;
        color: #525252;
        line-height: 1.5;
        padding: 8px;
    }

    .contact-us .call-us__map-link {
        display: inline-block;
        width: 32px;
        height: 32px;
        background-image: url(https://i.allo.ua/skin/frontend/enterprise/allomobile/images/sprite-all.svg?v=1.1);
        background-repeat: no-repeat;
        background-position: -64px -620px;
        background-size: 628px 1096px;
        background-color: #e0e0e0;
        border-radius: 3px;
        box-shadow: 0 2px 4px -2px #525252;
    }

    .contact-us .call-us__service {
        display: block;
        margin-top: 16px;
    }

    .contact-us .call-us__service-image {
        display: block;
        max-width: 100%;
        height: auto;
        margin: 0 auto;
    }

    /* MEDIA */
    @media screen and (min-width: 1025px) {
        .contact-us {
            max-width: none;
            padding: 20px 50px 64px 50px;
            border: none;
        }

        /* Tabs labels */
        .contact-us .contact-us__tabs {
            display: none;
        }

        /* Tabs Content */
        .contact-us .contact-us__content {
            display: flex;
        }

        .contact-us .contact-us__tab-content,
        .contact-us .contact-us__tab-content.active {
            display: block;
        }

        /*Call us section*/
        .contact-us .call-us {
            flex: auto 1 1;
        }

        .contact-us .call-us__title {
            display: block;
            color: #3e3e3e;
            font-size: 22px;
            font-weight: 400;
            line-height: 1.5;
            margin: 8px 8px 0 8px;
        }

        .contact-us .call-us__row-title {
            color: #525252;
            font-size: 16px;
            line-height: 1.3;
            letter-spacing: 0;
            margin: 0;
        }

        .contact-us .call-us__contact-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border: none;
            padding: 0;
            margin-bottom: 16px;
        }

        .call-us__contacts-wrapper {
            flex: auto 0 0;
        }

        .contact-us .call-us__contact {
            padding: 5px 8px;
            border: none;
        }

        .contact-us .call-us__phone {
            margin-right: 16px;
        }

        .contact-us .call-us__schedule-row {
            border: none;
            padding: 0;
            margin-bottom: 16px;
        }

        .contact-us .call-us__schedule {
            padding: 8px;
        }

        .contact-us .call-us__map-row {
            padding: 0;
        }

        .contact-us .call-us__map {
            padding: 0 8px;
        }

        /*Write us section*/
        .contact-us .write-us {
            flex: 496px 0 0;
            min-height: 422px;
            margin-left: 78px;
            border: 1px solid #dadada;
            border-radius: 3px;
            box-shadow: 0 0 7px #c5c5c5;
        }
    }
</style>

<div class="contact-us">
    <ul class="contact-us__tabs">
        <li class="contact-us__tab active" data-tab="call">Позвоните</li>
        <li class="contact-us__tab" data-tab="write">Напишите</li>
    </ul>

    <div class="contact-us__content">
        <div class="contact-us__tab-content call-us active" data-tab="call">
            <h3 class="call-us__title">Консультации и заказы по телефонам</h3>
            <div class="call-us__contact-row">
                <h5 class="call-us__row-title">Бесплатно по Украине:</h5>
                <div class="call-us__contacts-wrapper">
                    <div class="call-us__contact">
                        <span class="call-us__phone">(0-800) 300-100</span>
                        <a class="call-us__phone-button" href="tel:0800300100"></a>
                    </div>
                    <div class="call-us__contact">
                        <span class="call-us__phone">(0-800) 200-100</span>
                        <a class="call-us__phone-button" href="tel:0800200100"></a>
                    </div>
                </div>
            </div>
            <div class="call-us__contact-row">
                <h5 class="call-us__row-title">Согласно тарифа оператора:</h5>
                <div class="call-us__contacts-wrapper">
                    <div class="call-us__contact">
                        <span class="call-us__phone">(056) 790-12-34</span>
                        <a class="call-us__phone-button" href="tel:0567901234"></a>
                    </div>
                    <div class="call-us__contact">
                        <span class="call-us__phone">(056) 797-63-23</span>
                        <a class="call-us__phone-button" href="tel:0567976323"></a>
                    </div>
                </div>
            </div>
            <div class="call-us__schedule-row">
                <h5 class="call-us__row-title">График работы контакт-центра:</h5>
                <div class="call-us__schedule">
                    <span class="call-us__schedule-days">Ежедневно</span>
                    <span class="call-us__schedule-time">Круглосуточно</span>
                </div>
            </div>
            <div class="call-us__map-row">
                <h5 class="call-us__row-title">Магазины в Вашем городе</h5>
                <div class="call-us__map">
                    <span class="call-us__map-label">Перейти на карту магазинов</span>
                    <a href="//allo.ua/ru/offline_stores/" titlte="Перейти на карту магазинов" class="call-us__map-link"></a>
                </div>
            </div>
            <a href="//9005.allo.ua" target="_blank" title="Оцените наш уровень сервиса" class="call-us__service">
                <img src="https://i.allo.ua/media/Banner_Home/nps_ru.jpg" alt="Оцените наш уровень сервиса" class="call-us__service-image"/>
            </a>
        </div>

        <div class="contact-us__tab-content write-us" data-tab="write">
            <?php
                use Tsg\Feedback\Block\Widget\Form;

                /** @var Form $block */
            ?>
            <div id="feedback-widget">
                <script type="text/javascript">
                    window.feedbackWidgetConfig = <?= /* @noEscape */ $block->getJsonConfig()?>;
                </script>
            </div>

        </div>
    </div>
</div>

<script>
    ;(function () {
        var contactTabs = document.querySelector(".contact-us__tabs");
        contactTabs.addEventListener("click", changeActiveTab);

        /**
         * Change active tab
         */
        function changeActiveTab(event) {
            var tabElem = event.target.classList.contains("contact-us__tab") ? event.target : closest(event.target, ".contact-us__tab");

            if (!tabElem || !tabElem.dataset.tab ) return;
            var activeTab = tabElem.dataset.tab;

            var tabsElements = document.querySelectorAll(".contact-us__tab");
            for (var i = 0, length = tabsElements.length; i < length; i = i + 1) {
                tabsElements[i].dataset.tab === activeTab
                    ? tabsElements[i].classList.add("active")
                    : tabsElements[i].classList.remove("active");
            }

            var tabsContentElements = document.querySelectorAll(".contact-us__tab-content");
            for (var i = 0, length = tabsContentElements.length; i < length; i = i + 1) {
                tabsContentElements[i].dataset.tab === activeTab
                    ? tabsContentElements[i].classList.add("active")
                    : tabsContentElements[i].classList.remove("active");
            }
        }

        /**
         * Closest polyfill
         * @param { Object } el
         * @param { String } selector
         */
        function closest(el, selector) {
            var matches = el.webkitMatchesSelector ? 'webkitMatchesSelector' : (el.msMatchesSelector ? 'msMatchesSelector' : 'matches');
            while (el.parentElement) {
                if (el[matches](selector)) return el;
                el = el.parentElement;
            }
            return null;
        }
    })();
</script>